language: node_js
node_js:
- '0.12'
- '0.11'
- iojs
- iojs-v1.0.4
deploy:
  provider: heroku
  api_key:
    secure: Q+0OaoYCCdFwsqLapRqzYDD2z61DyCevIIr/J8FvtZYYXYxFKPkLoNdzNTSbKdODZjKYrwf4cLXhpBj77p8BrDrFOIldrrlz4/mUPk/H5bQymSYayJw1RrmrEHxMRzRRErwz0lblfgXCPqdhsDsOGykb8HL0pQy4gq8iRLgRCt7T7VgUWlcXQRcElKiQdplM+jXnQrvCX1TTz71x2xX4GE6sRLgoiaLQP5kk/c08UTWJn6gPK0RIe/7an1oGch17ZHXdn9s25JIEpOLx0i1vQhn8k8yGlZCjrUH2cEmMxUWW5SzXhn4NTRlbyeYAC77m1ZhR6ryR6B41bu+nrSn8w/fTub9TufneCJLAnTpPq022cWeoUlnLDLQpbRVe/9gd60eHD4vokO50ObfIDc3CYauYQm5ogsfEmYgu31dJwbd0OXdoup2w8Bn2iEyiN42Kr46DIq7CIpgAke04OxrTsPkzA0EJwLRSPFA+QX652CR5X73nv1snq8rU9o7Quu1y2YrA6oHpkTcoUlh6mOBA78dueuDTafrCC/xccV44SwRTns5+z7CW162jUSPmT44VzdzAiVNpLFFxUMj446kdd6mOQ16kyxaA8eZ+8HGBNbzWJMU/lpGvG8ypdZd2809DlpbPyVgnl+Ge4jL1Lt2TVSbKsIt6EHT+cIZZGkIK9Ms=
  app: still-springs-1199
